##################
# Example separate file overriding configuration
##################

userYank:
  root: "${HOME}/something"
  paths:
    build: "temp_dir_under_root"
    deploy: "${HOME}/other_absolute_path"

  # links:
      # airstrip:
      #   version: 1.0
      #   url: 'http://static.loft.sn.ackitup.net:4242/airstrip.yaml'


